# coding: utf-8

# flake8: noqa

"""
    Regula Document Reader Web API

    Regula Document Reader Web API  # noqa: E501

    The version of the OpenAPI document: 5.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "1.0.0"

# import apis into sdk package
from regula.documentreader.webclient.api.default_api import DefaultApi

# import ApiClient
from regula.documentreader.webclient.api_client import ApiClient
from regula.documentreader.webclient.configuration import Configuration
from regula.documentreader.webclient.exceptions import OpenApiException
from regula.documentreader.webclient.exceptions import ApiTypeError
from regula.documentreader.webclient.exceptions import ApiValueError
from regula.documentreader.webclient.exceptions import ApiKeyError
from regula.documentreader.webclient.exceptions import ApiAttributeError
from regula.documentreader.webclient.exceptions import ApiException
# import models into sdk package
from regula.documentreader.webclient.models.check_result import CheckResult
from regula.documentreader.webclient.models.chosen_document_type_result import ChosenDocumentTypeResult
from regula.documentreader.webclient.models.chosen_document_type_result_all_of import ChosenDocumentTypeResultAllOf
from regula.documentreader.webclient.models.container_list import ContainerList
from regula.documentreader.webclient.models.cross_source_value_comparison import CrossSourceValueComparison
from regula.documentreader.webclient.models.details_optical import DetailsOptical
from regula.documentreader.webclient.models.details_rfid import DetailsRFID
from regula.documentreader.webclient.models.doc_visual_extended_field import DocVisualExtendedField
from regula.documentreader.webclient.models.doc_visual_extended_info import DocVisualExtendedInfo
from regula.documentreader.webclient.models.document_format import DocumentFormat
from regula.documentreader.webclient.models.document_type import DocumentType
from regula.documentreader.webclient.models.document_type_recognition_result import DocumentTypeRecognitionResult
from regula.documentreader.webclient.models.document_types_candidates_list import DocumentTypesCandidatesList
from regula.documentreader.webclient.models.document_types_candidates_result import DocumentTypesCandidatesResult
from regula.documentreader.webclient.models.document_types_candidates_result_all_of import DocumentTypesCandidatesResultAllOf
from regula.documentreader.webclient.models.graphic_field import GraphicField
from regula.documentreader.webclient.models.graphic_field_type import GraphicFieldType
from regula.documentreader.webclient.models.graphic_fields_list import GraphicFieldsList
from regula.documentreader.webclient.models.graphics_result import GraphicsResult
from regula.documentreader.webclient.models.graphics_result_all_of import GraphicsResultAllOf
from regula.documentreader.webclient.models.image_data import ImageData
from regula.documentreader.webclient.models.images import Images
from regula.documentreader.webclient.models.images_available_source import ImagesAvailableSource
from regula.documentreader.webclient.models.images_field import ImagesField
from regula.documentreader.webclient.models.images_field_value import ImagesFieldValue
from regula.documentreader.webclient.models.images_result import ImagesResult
from regula.documentreader.webclient.models.images_result_all_of import ImagesResultAllOf
from regula.documentreader.webclient.models.lcid import LCID
from regula.documentreader.webclient.models.lexical_analysis_result import LexicalAnalysisResult
from regula.documentreader.webclient.models.lexical_analysis_result_all_of import LexicalAnalysisResultAllOf
from regula.documentreader.webclient.models.light import Light
from regula.documentreader.webclient.models.list_verified_fields import ListVerifiedFields
from regula.documentreader.webclient.models.one_candidate import OneCandidate
from regula.documentreader.webclient.models.original_symbol import OriginalSymbol
from regula.documentreader.webclient.models.process_params import ProcessParams
from regula.documentreader.webclient.models.process_request import ProcessRequest
from regula.documentreader.webclient.models.process_request_image import ProcessRequestImage
from regula.documentreader.webclient.models.process_response import ProcessResponse
from regula.documentreader.webclient.models.process_system_info import ProcessSystemInfo
from regula.documentreader.webclient.models.processing_status import ProcessingStatus
from regula.documentreader.webclient.models.raw_image_result import RawImageResult
from regula.documentreader.webclient.models.raw_image_result_all_of import RawImageResultAllOf
from regula.documentreader.webclient.models.rectangle_coordinates import RectangleCoordinates
from regula.documentreader.webclient.models.result import Result
from regula.documentreader.webclient.models.result_item import ResultItem
from regula.documentreader.webclient.models.rfid_location import RfidLocation
from regula.documentreader.webclient.models.rfid_origin import RfidOrigin
from regula.documentreader.webclient.models.scenario import Scenario
from regula.documentreader.webclient.models.source import Source
from regula.documentreader.webclient.models.source_validity import SourceValidity
from regula.documentreader.webclient.models.status import Status
from regula.documentreader.webclient.models.status_result import StatusResult
from regula.documentreader.webclient.models.status_result_all_of import StatusResultAllOf
from regula.documentreader.webclient.models.string_recognition_result import StringRecognitionResult
from regula.documentreader.webclient.models.symbol_candidate import SymbolCandidate
from regula.documentreader.webclient.models.symbol_recognition_result import SymbolRecognitionResult
from regula.documentreader.webclient.models.tfdsid_list import TFDSIDList
from regula.documentreader.webclient.models.text import Text
from regula.documentreader.webclient.models.text_available_source import TextAvailableSource
from regula.documentreader.webclient.models.text_data_result import TextDataResult
from regula.documentreader.webclient.models.text_data_result_all_of import TextDataResultAllOf
from regula.documentreader.webclient.models.text_field import TextField
from regula.documentreader.webclient.models.text_field_type import TextFieldType
from regula.documentreader.webclient.models.text_field_value import TextFieldValue
from regula.documentreader.webclient.models.text_result import TextResult
from regula.documentreader.webclient.models.text_result_all_of import TextResultAllOf
from regula.documentreader.webclient.models.transaction_info import TransactionInfo
from regula.documentreader.webclient.models.verification_result import VerificationResult
from regula.documentreader.webclient.models.verified_field_map import VerifiedFieldMap

