name: Back Merge

on:
  push:
    branches:
      - master
      - stable

jobs:
  back-merge:
    uses: regulaforensics/reusable-workflows/.github/workflows/back-merge.yaml@0a60f3315e9d75b6966ff088cf5597415f87b3cf # main
    with:
      source_branch: ${{ github.ref_name }}
      merge_pairs: "master:stable,stable:develop"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
