name: Back Merge

on:
  push:
    branches:
      - master
      - stable

jobs:
  back-merge:
    uses: regulaforensics/reusable-workflows/.github/workflows/back-merge.yaml@887c6589b486a4932ea7e7e8c76404b8ac99c6c6 # main
    with:
      source_branch: ${{ github.ref_name }}
      merge_pairs: "master:stable,stable:develop"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
