name: run smoke test

on:
  pull_request:
    branches:
      - develop
      - master
      - stable

jobs:
  run_smoke_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel
      - name: Install test dependencies
        run: pip install -e ./
      - name: Run smoke test
        run: python example.py
        working-directory: example
        env:
          API_BASE_PATH: "https://nightly-api.regulaforensics.com"
