name: test publish pypi package

on:
  push:
    branches:
      test_publish

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel
          python -m pip install --upgrade pipenv
      - name: Install dependencies
        run: pipenv install --dev
      - name: Publish package
        run: |
          pipenv run pipenv install
          pipenv run python setup.py sdist bdist_wheel
        env:
          PACKAGE_VERSION_TO_PUBLISH: "7.4.46"